### ISSUE TITLE
[FEAT] 강아지 삭제 시 강아지 관련 정보도 삭제

### ISSUE THREAD

**Issue by 0sunset0** [Semoban/meongcare-back#100]
## Description
각 엔티티를 dogId로 찾아오는 메서드도 없는 경우가 많아서 이슈 분리했습니다
- 강아지 삭제할 때 강아지 관련 정보(영양제, 사료 증)도 삭제를 해야 하는데 
엔티티 간 연관관계가 id 참조인 곳도 있고 아닌 곳도 있어서 jpa의 장점을 활용하지 못하고 있다는 생각이 들었습니다!

- 그리고 데이터로 dto로 가져오는 부분이 많아서  [강아지 id로 사료 id 찾아오기 ➡️ 사료 id로 사료 찾아와서 소프트 딜리트] 를 해야 하다보니 코드도 더러워지고
- 리포지토리로 각 엔티티를 삭제하니까  (영양제 시간 삭제는 영양제의 책임인데) 모든 책임이 강아지에게 있다는 느낌도 있구요

## ToDo
- [ ] 각 엔티티 dogId로 찾아오는 메서드 만들기
- [ ] 강아지 삭제 시 다른 엔티티도 삭제 되게 하기
- [ ] 영양제 삭제 시, 영양제 루틴도 삭제해야 함

## ETC
-

**Comment by choigy1001** [comment]
1. 연관관계를 통해서 삭제하는 것도 물론 좋지만, delete 쿼리가 N+1 마냥 나가면서  삭제되는걸로 알고 있습니다. 
그래서 저는 orphanremoval 옵션보다는, 쿼리를 통해 직접 수행하는게 로직단에서도 바로 파악할 수 있기에 이를 선호하는 편입니다. (이건 스타일의 차이같네요)
2. 두 번째는 쿼리에서 해결할 수 있는 부분이 아닌가 생각이드네요.
3. 강아지 삭제에서 많은 Repository에 의존하는게 맞는 말이긴 합니다. 하지만 그만큼 강아지 엔티티가 모든 엔티티에 연관관계를 가지고 있기 때문에 발생하는 문제라, 이 부분은 저희가 orphanremoval 옵션을 선택했더라면 해결할 수 있었지만, 그게 아니기 때문에 감안하고 가야할 거 같습니다.

**Comment by 0sunset0** [comment]
1. 저도 근영님 의견이 좋은거 같습니다 감사합니다!!
2. 그러네요 .... 감사합니닷!
3. 사실 저는 강아지 서비스가 '(영양제 기록도 삭제하는) 영양제 서비스 함수'를 사용하게 하고 싶었는데.. (나중에라도 순환참조가 생길 수 있으니) 그냥 영양제 리포지토리를 의존하게 해야할 거 같습니다 의견 감사합니다😊
